server:
  port: 1881
spring:
  datasource:
    url: jdbc:h2:file:./data/demo-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false